import socket
server_socket = socket.socket(socket.AF_INET, socket.SOCK_STREAM, socket.IPPROTO_TCP)
server_socket.bind(('127.0.0.1', 50000))
server_socket.listen(1)
connection, client_address = server_socket.accept()
connection.sendall(b'Hello, client!')
data = connection.recv(1024)
print('Received from client:', data.decode())
connection.close()
server_socket.close()
