#!/usr/bin/env python

import datetime

default = "No value set"

body = """<html>
<head>
<title>WSGI Example</title>
</head>
<body>
<p>Hey there, this page has been generated by {software}, running at {path}</p>
<p>Today is {month} {date}, {year}.</p>
<p>This page was requested by IP addres {client_ip}.</p>
</body>
</html>"""

def application(environ, start_response):
    #import pprint
    #pprint.pprint(environ)

    response_body = body

    environ['SERVER_SOFTWARE'] = "OVERRIDE/1.0"
    status = '404 Not Found'

    response_headers = [
        ('Content-Type', 'text/html'),
        ]

    response_body = body.format(
        software=environ.get('SERVER_SOFTWARE', default),
        path=environ.get('PATH_INFO', default),
        month=datetime.datetime.now().strftime('%B'),
        date=datetime.datetime.now().strftime('%d'),
        year=datetime.datetime.now().strftime('%Y'),
        client_ip=environ.get('REMOTE_ADDR', default)
    )

    start_response(status, response_headers)

    return [response_body.encode('utf-8')]

if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    server = make_server('localhost', 8000, application)
    print("Serving on port 8000...")
    server.serve_forever()

