# Generated by Django 5.2.5 on 2025-08-12 23:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Platform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=100)),
                ('url', models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Show',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('season', models.SmallIntegerField()),
                ('image_url', models.URLField(blank=True)),
                ('watched', models.BooleanField(default=False)),
                ('genres', models.ManyToManyField(blank=True, to='watchlist.genre')),
                ('platform', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='watchlist.platform')),
            ],
        ),
    ]
